[project]
name = "ansible-osx"
version = "0.1.0"
description = "Mac OS X configuration management using Ansible"
requires-python = ">=3.14"
dependencies = [
    "ansible>=13.1.0",
    "ansible-lint>=25.12.1",
]
