---
- name: Upgrading homebrew formulae
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install command line tools using homebrew
  community.general.homebrew:
    name:
      - curl
      - fzf
      - gh
      - ghq
      - git
      - gnu-sed
      - gnu-tar
      - jq
      - mise
      - starship
      - tree
      - wget
      - yq
