---
- name: Configure osx
  ansible.builtin.include_tasks: ../roles/common/tasks/osx.yml
- name: Configure zsh
  ansible.builtin.include_tasks: ../roles/common/tasks/zsh.yml
- name: Configure git
  ansible.builtin.include_tasks: ../roles/common/tasks/git_config.yml
- name: Install command line tools
  ansible.builtin.include_tasks: ../roles/common/tasks/cli.yml
- name: Configure docker
  ansible.builtin.include_tasks: ../roles/common/tasks/docker.yml
- name: Configure ssh
  ansible.builtin.include_tasks: ../roles/common/tasks/ssh_config.yml
